### ISSUE TITLE
Hang up of unit test "exchange_manager"

### ISSUE THREAD

**Issue by MaximilienNaveau** [machines-in-motion/shared_memory#5]
# Problem in unitest hanging

The unit-test "exchange_manager" hangs up during the continuous integration and sometimes on my computer too. Which makes the CI fail but with no real information on what failed...

# Action taken

I disabled it from the code. One need to investigate the reasons for this hang up.

**Comment by jviereck** [comment]
Thanks for reporting this Max.

A few things:
- in the future, could you point to the PR/commit where you disabled the code? This makes it easier when reading the issue to get the context (in this case the commit is [1]).
- given that this is crucial for our robot communication, I would voice to make this a P0 bug - inputs?
- who is going to track down this bug? 
- is this a regression - can you find a regression window for this bug?

In case you have troubles to track this down, happy to take a look.

[1]: https://github.com/machines-in-motion/shared_memory/commit/88751756376ba5dfc7e70201c3decd412ce7b705

**Comment by vincentberenz** [comment]
I will look into this today

**Comment by vincentberenz** [comment]
This issue can be closed after merge:

https://github.com/machines-in-motion/shared_memory/pull/6

**Comment by MaximilienNaveau** [comment]
This file "include/shared_memory/exchange_manager_memory.hpp" lacks documentation

**Comment by vincentberenz** [comment]
@MaximilienNaveau 
exchange_manager_memory.hpp is not part of the API, it is meant to be used internally by exchange_manager_producer/consumer. 
What I will do: move it to include/shared_memory/internal and set the code in namespace shared_memory::internal.
Can we have doxygen skipping include/*/internal in all packages ?

**Comment by MaximilienNaveau** [comment]
Good thinking. We should also make sure that Catkin does not install the files then.
And during the creation of the library you can put the header as source file. So it is embedded in the ".so"
